# Generated by Django 2.2.5 on 2019-10-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('events', '0001_initial'),
        ('users', '0004_auto_20190916_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='送信者')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='紐付くイベント')),
            ],
        ),
        migrations.CreateModel(
            name='InnerGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='タイトル')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='group.Group', verbose_name='投稿グループ')),
            ],
        ),
        migrations.CreateModel(
            name='HasReadInnerGroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('group_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.InnerGroupMessage', verbose_name='グループ内メッセージ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='受取人')),
            ],
        ),
        migrations.CreateModel(
            name='HasReadEventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('event_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.EventMessage', verbose_name='イベントメッセージ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='受取人')),
            ],
        ),
        migrations.CreateModel(
            name='GroupApplyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_receiver', to='users.Profile', verbose_name='管理者')),
                ('applied_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='応募者')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_message', to='group.Group', verbose_name='応募したグループ')),
            ],
        ),
        migrations.CreateModel(
            name='EventJoinedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('joined_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_apply_receiver', to='users.Profile', verbose_name='管理者')),
                ('applied_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='応募者')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='応募したイベント')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyAdministratorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='申請理由')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.ForeignKey(default='脱退した管理者', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='applied_administrator', to='users.Profile', verbose_name='管理者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='管理者となるグループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_user', to='users.Profile', verbose_name='受取人')),
            ],
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='受取人')),
            ],
        ),
    ]
