# Generated by Django 2.2.4 on 2019-08-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ImageField(blank=True, null=True, upload_to='profile_image/%y/%m/%d/', verbose_name='プロフィール画像')),
                ('profile', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='プロフィール')),
                ('sex', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('X', '第3の性'), ('N/A', '回答しない')], max_length=3, verbose_name='性別')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢')),
                ('twitter_link', models.URLField(blank=True, default='', null=True, verbose_name='Twitterアカウントのリンク')),
                ('facebook_link', models.URLField(blank=True, default='', null=True, verbose_name='Facebookアカウントリンク')),
                ('instagram_link', models.URLField(blank=True, default='', null=True, verbose_name='Instagramアカウントのリンク')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
