# Generated by Django 2.2.4 on 2019-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190829_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性'), ('X', '第3の性'), ('N/A', '回答しない')], default=None, max_length=3, verbose_name='性別'),
        ),
    ]
