# Generated by Django 2.2.5 on 2019-10-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('users', '0004_auto_20190916_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='タイトル')),
                ('content', models.CharField(max_length=1000, verbose_name='本文')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('detail_place', models.CharField(max_length=200, verbose_name='活動場所')),
                ('event_day', models.DateField(verbose_name='開催日')),
                ('event_end_day', models.DateField(blank=True, default='', null=True)),
                ('time_description', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='開催時間・予定日の補足情報')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='group_event_image1/%y/%m/%d/', verbose_name='イベント画像1枚目')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='group_event_image2/%y/%m/%d/', verbose_name='イベント画像2枚目')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='group_event_image3/%y/%m/%d/', verbose_name='イベント画像3枚目')),
                ('joinned_user', models.ManyToManyField(blank=True, to='users.Profile', verbose_name='参加者')),
                ('posted_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='投稿グループ')),
                ('prefecture', models.ManyToManyField(to='group.GroupPrefecture', verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='コメント')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント日')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='紐付く投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='EventCommentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='管理者')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventComment', verbose_name='コメント')),
            ],
        ),
    ]
