# Generated by Django 2.2.5 on 2019-10-03 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190916_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'スポーツ全般'), ('2', 'ランニング'), ('3', '野球'), ('4', 'サッカー'), ('5', 'テニス'), ('6', 'ソフトボール'), ('7', 'フットサル'), ('8', 'バスケットボール'), ('9', 'バレーボール'), ('10', 'バドミントン'), ('11', '卓球'), ('12', '登山'), ('13', 'ハイキング'), ('14', 'ダンス'), ('15', 'ヨガ・ピラティス'), ('16', 'ボルダリング'), ('17', 'ダーツ'), ('18', '筋トレ'), ('19', 'スキー'), ('20', 'スノーボード'), ('21', 'ゴルフ'), ('22', '水泳'), ('23', 'サーフィン'), ('24', 'ダイビング'), ('25', 'トライアスロン'), ('99', 'その他のスポーツ・アウトドア'), ('101', '飲み会'), ('102', '勉強会'), ('103', '芸術'), ('104', '散歩'), ('105', '料理'), ('106', 'グルメ'), ('107', '写真'), ('108', '映画'), ('109', '音楽'), ('110', 'ビジネス'), ('111', 'ゲーム'), ('112', '旅行'), ('113', '健康・ダイエット'), ('114', 'ボランティア'), ('115', '起業'), ('116', '釣り'), ('117', '手芸'), ('118', 'イベント'), ('119', 'その他の趣味'), ('201', '交流会'), ('202', '国際交流'), ('203', '企画'), ('204', 'その他の社会・交流')], max_length=100, unique=True, verbose_name='カテゴリー')),
                ('category_sort', models.CharField(choices=[('1', 'スポーツ・アウトドア'), ('2', '文化系'), ('3', '社会活動')], default='1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(choices=[('1', '学生'), ('2', '社会人'), ('3', 'シニア')], max_length=100, unique=True, verbose_name='年代')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPrefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(choices=[('1', '北海道'), ('2', '青森県'), ('3', '岩手県'), ('4', '宮城県'), ('5', '秋田県'), ('6', '山形県'), ('7', '福島県'), ('8', '茨城県'), ('9', '栃木県'), ('10', '群馬県'), ('11', '埼玉県'), ('12', '千葉県'), ('13', '東京都'), ('14', '神奈川県'), ('15', '新潟県'), ('16', '富山県'), ('17', '石川県'), ('18', '福井県'), ('19', '山梨県'), ('20', '長野県'), ('21', '岐阜県'), ('22', '静岡県'), ('23', '愛知県'), ('24', '三重県'), ('25', '滋賀県'), ('26', '京都府'), ('27', '大阪府'), ('28', '兵庫県'), ('29', '奈良県'), ('30', '和歌山県'), ('31', '鳥取県'), ('32', '島根県'), ('33', '岡山県'), ('34', '広島県'), ('35', '山口県'), ('36', '徳島県'), ('37', '香川県'), ('38', '愛媛県'), ('39', '高知県'), ('40', '福岡県'), ('41', '佐賀県'), ('42', '長崎県'), ('43', '熊本県'), ('44', '大分県'), ('45', '宮崎県'), ('46', '鹿児島県'), ('47', '沖縄県')], max_length=10, unique=True, verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='グループ名')),
                ('subtitle', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='サブタイトル')),
                ('activity_description', models.CharField(default='', max_length=3000, validators=[django.core.validators.MinLengthValidator], verbose_name='活動内容')),
                ('mood', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='雰囲気')),
                ('welcome_person', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='こんな人に来て欲しい')),
                ('number_of_members', models.IntegerField(default=1, verbose_name='会員数')),
                ('sex_ratio', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='ジェンダー比')),
                ('max_age', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('cost', models.CharField(default='', max_length=300, verbose_name='会費')),
                ('day', models.CharField(default='', max_length=200, verbose_name='活動日・活動頻度')),
                ('last_comment', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='最後に一言')),
                ('recruiting', models.BooleanField(default=True, verbose_name='メンバー募集')),
                ('detail_place', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='詳細な活動場所')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='設立年')),
                ('display', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('recruit_member', models.BooleanField(default=True, verbose_name='新規メンバー募集')),
                ('image1', models.ImageField(default='', upload_to='group_profile_image1/%y/%m/%d/', verbose_name='グループトップ画像')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='group_profile_image2/%y/%m/%d/', verbose_name='グループ画像2枚目')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='group_profile_image3/%y/%m/%d/', verbose_name='グループ画像3枚目')),
                ('administrator', models.ManyToManyField(related_name='managing_group', to='users.Profile')),
                ('applied_user', models.ManyToManyField(blank=True, default='なし', related_name='applied_group', to='users.Profile')),
                ('before_administrator', models.ManyToManyField(blank=True, related_name='before_administrator', to='users.Profile')),
                ('category', models.ManyToManyField(help_text='最大5個まで選択可', to='group.GroupCategory')),
                ('generation', models.ManyToManyField(help_text='複数選択可', to='group.GroupGeneration', verbose_name='年代')),
                ('member', models.ManyToManyField(related_name='belonging_group', to='users.Profile')),
                ('prefecture', models.ManyToManyField(help_text='最大5つまで選択可', to='group.GroupPrefecture', verbose_name='都道府県')),
            ],
            options={
                'ordering': ['-number_of_members'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['-number_of_members'], name='group_group_number__9653ad_idx'),
        ),
    ]
