# Generated by Django 2.2.5 on 2019-10-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20190916_1406'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='タイトル')),
                ('content', models.CharField(max_length=1000, verbose_name='本文')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='group_blog_image1/%y/%m/%d/', verbose_name='ブログ画像1枚目')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='group_blog_image2/%y/%m/%d/', verbose_name='ブログ画像2枚目')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='group_blog_image3/%y/%m/%d/', verbose_name='ブログ画像3枚目')),
                ('posted_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group', verbose_name='投稿グループ')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='コメント')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント日時')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog', verbose_name='紐付く投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCommentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False, verbose_name='既読')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='管理者')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.BlogComment', verbose_name='コメント')),
            ],
        ),
    ]
